[FT] Extended periods of timeout and grace period to six months
andela/hc-june-bunnies pull request #22
Opened 2018-07-11 18:27 UTC by loicemeyo

*Problem*
Currently the user can only set checks with a limited timeout and grace period - each of only of 30 days. This should be extended as some crone jobs can run longer than 30 days.

*Solution*
- Extend maximum periods from one month to six months on the forms file
-Fix tests to accommodate  samples of extended timeout and grace periods
-Change intervals on the modal for the period-slider and grace-slider

*Relevant Pivotal Tracker story*
https://www.pivotaltracker.com/story/show/158532878

*Screenshot to demonstrate solved problem*
![image](https://user-images.githubusercontent.com/37342753/42592007-0901010c-8551-11e8-89d7-adbc10fdcb7b.png)

2018-07-11 19:51 UTC, simiyu1 requested changes
Commendable use of comments and easy to follow code. Good work, however your tests are failing. Here are some things to watch out for..

Please check your test files for the function 'test_hc_duration_work'. Your assert is looking for "6 months" but finds "1 six_months"

Check also the test function 'test_timeout_too_large', ensure that it can be found because it yeilds a 404 error.

Confirm that '-webkit-text-size-adjust' has been correctly named. Is the hyphen part of the name?

2018-07-12 03:48 UTC, karanjaE requested changes

2018-07-12 03:48 UTC, ranchow commented on static/js/checks.js
> +    //To change the intervals on the period slider for viewing and choosing timeouts"""
you don't need the docstring quotes in js files

2018-07-12 03:48 UTC, ranchow commented on static/js/checks.js
> +    //To change the intervals on the grace slider for viewing and choosing grace periods"""
here too

2018-07-12 06:11 UTC, thoth-ky reviewed
Fix failing tests

2018-07-12 10:52 UTC, simiyu1 approved these changes

2018-07-13 04:35 UTC, karanjaE approved these changes

2018-07-13 04:38 UTC, merged