Em/configure periodic reports
andela/hc-june-bunnies pull request #24
Opened 2018-07-12 08:49 UTC by miritih

**Problem**
Currently, the dashboard only allows subscribing to monthly report. 

**Solution**
- Changed  reports sending to be user configurable to either be daily, weekly or monthly. 
- Added weekly and daily Radio boxes on the UI
- Add test to check can send daily, weeky, and monthly reports.  

**Screenshots**

<img width="1680" alt="screen shot 2018-07-12 at 11 48 05" src="https://user-images.githubusercontent.com/6532136/42622637-830e7c54-85c9-11e8-8ed9-5fe5af117f4d.png">

**Relevant Pivotal Tracker story**
https://www.pivotaltracker.com/story/show/158532875

2018-07-12 10:52 UTC, thoth-ky approved these changes
Good work

2018-07-12 10:59 UTC, simiyu1 approved these changes
Good coding looks clean to me...

2018-07-12 11:12 UTC, loicemeyo approved these changes
This is amazing implementation Eric

2018-07-12 16:26 UTC, karanjaE requested changes

2018-07-12 16:26 UTC, karanjaE commented on .env.example
> +export SITE_ROOT="http://localhost:8000"
missing single empty line at the end of the file

2018-07-12 16:26 UTC, karanjaE commented on hc/accounts/forms.py
> +    reports_allowed = forms.CharField(required=True)
why was the field changed to charfield?

2018-07-12 16:26 UTC, karanjaE commented on hc/accounts/tests/test_profile.py
> +
remove the empty spaces

2018-07-12 16:33 UTC, miritih commented on hc/accounts/forms.py
> +    reports_allowed = forms.CharField(required=True)
To accommodate checking daily, weekly or monthly I'm saving the period as a string. The earlier was a boolean checking if monthly reports were enabled or not. Considering we are checking more than 3 variables here I decided to change this to a charfield.

2018-07-12 16:48 UTC, ranchow commented on hc/accounts/forms.py
> +    reports_allowed = forms.CharField(required=True)
got it.

2018-07-13 04:33 UTC, karanjaE approved these changes

2018-07-13 04:33 UTC, merged